### ISSUE TITLE
Binomial family example errors during model fit

### ISSUE THREAD

**Issue by rangi513** [stitchfix/MomentMixedModels#5]
Hello, I was attempting to build some moment mixed effects models and `family = "gaussian"` seems to work fine, but when I attempt to run the example [here](https://github.com/stitchfix/MomentMixedModels/blob/master/src/main/scala/com/stitchfix/mbest/Examples.scala#L55-L86) for `family = "binomial"` I get an error:

```
Caused by: java.lang.IllegalArgumentException
	at breeze.linalg.svd$.breeze$linalg$svd$$doSVD_Double(svd.scala:112)
	at breeze.linalg.svd$Svd_DM_Impl$.apply(svd.scala:40)
	at breeze.linalg.svd$Svd_DM_Impl$.apply(svd.scala:39)
	at breeze.generic.UFunc$class.apply(UFunc.scala:48)
	at breeze.linalg.svd$.apply(svd.scala:23)
	at breeze.linalg.rank$$anon$1.apply(rank.scala:27)
	at breeze.linalg.rank$$anon$1.apply(rank.scala:25)
	at breeze.generic.UFunc$class.apply(UFunc.scala:48)
	at breeze.linalg.rank$.apply(rank.scala:21)
	at com.stitchfix.mbest.FirthLogisticRegression$.firthLogisticRegression(FirthLogisticRegression.scala:29)
	at com.stitchfix.mbest.MixedEffectsRegression$.estimateBinomial_η0(MixedEffectsRegression.scala:240)
	at com.stitchfix.mbest.MixedEffectsRegression$.estimate_η0(MixedEffectsRegression.scala:212)
	at com.stitchfix.mbest.MixedEffectsRegression$$anonfun$estimateGrouped_η0$1.apply(MixedEffectsRegression.scala:196)
	at com.stitchfix.mbest.MixedEffectsRegression$$anonfun$estimateGrouped_η0$1.apply(MixedEffectsRegression.scala:195)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:185)
	at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$treeReduce$1$$anonfun$16.apply(RDD.scala:1057)
```

When I assembled a JAR using sbt assembly it said it passed all unit tests, but when I go to run the code in a spark shell for the binomial example this error occurs.

I'm curious if I'm inputting something incorrectly or if there is actually something not working properly.

**Comment by rangi513** [comment]
Any ideas here? @kschmaus

**Comment by kschmaus** [comment]
@rangi513 I'll take a look at this today. Sorry for not getting back to you in December!

**Comment by hougs** [comment]
@rangi513 What is the exact code that you executed that gave you this error?

**Comment by rangi513** [comment]
``` 
val binomialSimSchema = StructType(Array(
    StructField("x1", DoubleType, true),
    StructField("x2", DoubleType, true),
    StructField("y", DoubleType, true),
    StructField("group_id", StringType, true)))

val binomialSimData = {
  spark
    .read.format("csv")
    .option("header", "true")
    .schema(binomialSimSchema)
    .load("/FileStore/tables/binomial_sim.csv")
}

val logisticModelFitter = {
  new MixedEffectsRegression()
    .setResponseCol("y")
    .setFixedEffectCols(Seq("x1", "x2"))
    .setRandomEffectCols(Seq("x1"))
    .setFamilyParam("binomial")
    .setGroupCol("group_id")
}

val logisticModel = logisticModelFitter.fit(binomialSimData)
```
The data loads in and the MixedEffectsRegression object is created, but then when I go to use the `.fit` method I receive the above error messaging.

**Comment by kschmaus** [comment]
Morning @rangi513! Unfortunately, I haven't been able to reproduce your exception, either in the binomial model fit from the examples directory, or from the binomial model fit in the unit tests. All run as expected on my computer. 

I think the next step is to determine what is different from your setup vs mine. Can you let me know what commit sha you are running, and what version of scala you are using? Also, I've noticed from your above example that you're loading data from a different directory (`.load("/FileStore/tables/binomial_sim.csv")`) as the example file (`.load("data/binomial_sim.csv")`). Do you get the same exception with the later line?

**Comment by rangi513** [comment]
I'm running this commit a698b47d6b80e806b4546b6501d922419020b6d2 version 0.1.0 of this library. I'm running on a Databricks cluster with Spark 2.3.1 and Scala 2.11 which is why the filepath is changed (since I'm manually uploading the file to Databricks file store). The linear regression test with sleepstudy.csv works correctly with this same method but using `setFamilyParam("gaussian")` instead. 

I've tracked the error down to doSVD_Double() in (scalanlp) breeze.linalg where it tries to initialize a new object `val info = new intW(0)`.  https://github.com/scalanlp/breeze/blob/f99528580393d5b667c4cc3d8f5274c537322b32/math/src/main/scala/breeze/linalg/functions/svd.scala#L95
This then errors out on line 122 throwing an illegal argument exception. 
https://github.com/scalanlp/breeze/blob/f99528580393d5b667c4cc3d8f5274c537322b32/math/src/main/scala/breeze/linalg/functions/svd.scala#L122

Do you think it could be an issue with the version of scala/spark I am running or a missing dependency?

**Comment by kschmaus** [comment]
@rangi513 Can you share the code use used to manually upload the binomial data to your file store? I continue to think (hope) that's the likely source of the error/discrepancy , since your tests did run.

**Comment by rangi513** [comment]
@kschmaus Thanks for your responsiveness in helping through this issue. Unfortunately I uploaded the file through a drag and drop UI so there is no code to share. But it is effectively the same as using the Databricks API to `cp` the file into a file path. 

To take a step back, I was originally trying to use this package to fit a model to a larger dataset with a binary response. I was trying to debug and found that I received the same error message with the test dataset from this repository so I decided I would share the more reproducible example here. I did not receive the error message when trying to fit the linear (gaussian) response.

If we can narrow down the conflict I would definitely be willing to help contribute with a PR to this repo. I'm just currently unsure where else to look. Could you share generally how your cluster is setup and which versions of scala/spark you are running with this code? 

One thing I just realized when I originally built the jar with the `build.sbt` file is I commented out this dependency: 
```
// "com.stitchfix.algorithms.spark" %% "sfs3" % "0.7.0-spark2.2.0",
```
since I didn't have access to it (I'm assuming `com.stitchfix.algorithms.spark` is internal to Stichfix) and it wasn't needed for the linear case, but maybe its necessary for the binomial case?

**Comment by hougs** [comment]
The issue is likely because you are running code compiled and packaged with spark 2.2.0 in a cluster running spark 2.3.1. The best way to write a library for other people to run on their spark clusters is to mark the spark dependencies as 'provided', meaning users runtime environments will have those dependencies available and they deps should not be packaged with the final jar. In our SBT file we have:

`"org.apache.spark" %% "spark-core" % "2.2.0",`

and those lines should actually be

`"org.apache.spark" %% "spark-core" % "2.2.0" % "provided",`

Try changing those spark dep lines in the buildl.sbt file and let us know how that goes.

**Comment by rangi513** [comment]
I tried `% "provided"` on each of the spark components and assembled the new .jar file, attached it to my cluster and tried it on Databricks runtime 5.2 and 3.5 LTS (just two different runtime configurations). The jar built much more quickly because the dependencies weren't installed with the jar, the tests still passed, but this still did not solve the error message. I also tried adding the `% "provided"` to breeze, commons-math3, and scalatest since all these are already provided with the Databricks runtime environments I was using and it still produced the same error message. There are no other libraries attached to my cluster at the moment other than what comes standard with those runtime environments.

I have narrowed down that the data import is likely not the problem because I can fit a model with the `.setFamilyParam("gaussian")` method on the same `binomial_sim.csv` dataset and can use that model to predict. It is only when I switch the argument to `"binomial"` that this error message occurs. Are there specific dependencies you know of that are used in the binomial case that are not used in the gaussian case? 

Let me know if there is any other information I can provide to help.

**Comment by rangi513** [comment]
Update: I have narrowed down the problem to this line in 
https://github.com/scalanlp/breeze/blob/f99528580393d5b667c4cc3d8f5274c537322b32/math/src/main/scala/breeze/linalg/functions/svd.scala#L122
where `(info.val < 0)`. The only place where this is updated after it is initialized is in this piece of code referencing lapack:
```
lapack.dgesdd(
      mode.JOBZ,
      m,
      n,
      cm.data,
      scala.math.max(1, m),
      S.data,
      U.data,
      scala.math.max(1, m),
      Vt.data,
      LDVT,
      work,
      work.length,
      iwork,
      info)
```
This is from the fommil.netlib package. The unit tests for the binomial mixed effects model works locally (OSX) in intellij and when I `build assembly` but it does not work in Databricks. The only difference that I have been able to find between these two systems is Databricks seems to be running a native linux version of these.
```
  "com.github.fommil" % "jniloader" % "1.1",
  "com.github.fommil.netlib" % "native_ref-java" % "1.1",
  "com.github.fommil.netlib" % "native_ref-java-natives" % "1.1",
  "com.github.fommil.netlib" % "native_system-java" % "1.1",
  "com.github.fommil.netlib" % "native_system-java-natives" % "1.1",
  "com.github.fommil.netlib" % "netlib-native_ref-linux-x86_64-natives" % "1.1",
  "com.github.fommil.netlib" % "netlib-native_system-linux-x86_64-natives" % "1.1",
```
However I cannot test this locally since I'm not running linux locally.

**Comment by hougs** [comment]
So, looking at how this info value is set, its funny FORTRAN way to signal an exception. Fine, whatever. In breeze, the integer value isn't recorded in the exception passed back to us. There actually is information contained in there -- the value corresponds to what arguments passed to the method was invalid. [(look at lapack 3.1.1 and search for 'Test the input arguments')](http://www.netlib.org/lapack/lapack-3.1.1/html/dgesdd.f.html) Without knowing the value of info (-3? -5?) it is hard to know what is going wrong exactly. This may be the type of thing a support ticket with databricks would solve.

**Comment by rangi513** [comment]
I'm going to file a support ticket with Databricks and see if they can help. In the meantime I might shade some of the packages and add a line of code underneath to see if I can get the info.val to print out prior to the exception.

**Comment by anayyar82** [comment]
Hello @kschmaus, Can you confirm if the issue is library dependent, I built the same in Spark 2.3 and 2.4 - on Linux and I get the same error.

**Comment by rangi513** [comment]
I spent a few minutes playing with this package again today with a fresh set of eyes and found that if I removed the `rank(X)` assertion here (using the rank method from `breeze.linalg`) then all tests pass even in Databricks (meaning it works across different operation systems). 
https://github.com/stitchfix/MomentMixedModels/blob/master/src/main/scala/com/stitchfix/mbest/FirthLogisticRegression.scala#L29
@kschmaus Do you have a reference in the Perry paper or another that could help explain to me why this assertion is required? If it is necessary, there may be another trivial way to implement `rank()` on a DenseVector without using the breeze dependency. If not, removing this line could solve the issues I was encountering.

**Comment by kschmaus** [comment]
@rangi513 Thank you for continuing to look at this! I _believe_ I'm thinking of section 3.4, where they document the steps for setting up a Firth Regression. In step (a)(i), we construct a matrix $F_{0i}$ with full column rank. Now, when we call this method within the package (https://github.com/stitchfix/MomentMixedModels/blob/master/src/main/scala/com/stitchfix/mbest/MixedEffectsRegression.scala#L240), the `UD` matrix should have full column rank, so I'm probably open towards removing this line. 

@rangi513 If you could prepare a pull request that passes all tests on your system, and all it amounted to was removing this line, I'd happily merge it into master, assuming tests passed on my end. How does that sound?
